id: I9A323294
legacy_id: P010494
ocr_import_info:
  bdrc_scan_id: W00EGS1016963
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T09:27:14'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T14:31:28.560326+00:00'
last_modified: 2022-08-30 22:35:02.366810
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1016963
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1016963
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། པདྨ་ཉིན་བྱེད་དབང་པོ། ༼དཔལ་སྤུངས་པར་མ།༽
  author: སི་ཏུ ༠༩་པདྨ་ཉིན་བྱེད་དབང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.6625934477748979
  ocr_word_median_confidence_index: 0.7300000190734863
quality: null
bases:
  I00EGS1016966:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016966
      total_pages: 834
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I00EGS1016966.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6502237054952228
    legacy_id: v002
  I00EGS1016965:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016965
      total_pages: 798
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00EGS1016965.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6779062870622447
    legacy_id: v001
  I00EGS1016967:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016967
      total_pages: 782
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I00EGS1016967.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6596860873510672
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
